(()=>{"use strict";
const U="https://eyjjmacxxcmdzkfqxifo.supabase.co/rest/v1",K="sb_publishable_6ZnjmE7NccV2hrOOZ-FeNQ_OvP3rLlS";
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
let GAMES=[];
async function get(path){const r=await fetch(U+path,{headers:{apikey:K,Authorization:"Bearer "+K}});if(!r.ok)throw 0;return r.json()}
async function loadGames(){try{GAMES=await get("/game_catalog?select=slug,name,unit,tag,image_url,description&active=eq.true&order=sort_order.asc")}catch{GAMES=[]}}
async function loadHome(){try{const a=await get("/home_content?select=section_key,title,subtitle,description,image_url,link_url&active=eq.true&order=sort_order.asc");const by=Object.fromEntries(a.map(x=>[x.section_key,x]));
 const hero=by.hero;if(hero){const h=document.querySelector(".neo-hero h1"),p=document.querySelector(".neo-hero-copy>p"),k=document.querySelector(".neo-kicker");if(h){const parts=hero.title.split("\n");h.innerHTML=parts.map((x,i)=>i?"<span>"+esc(x)+"</span>":esc(x)).join("<br>")}if(p)p.textContent=hero.description;if(k)k.innerHTML='<span class="pulse-dot"></span> '+esc(hero.subtitle||"GAME RUSH IRAQ")+" <b>LIVE</b>";const img=document.querySelector(".neo-media-main img");if(img&&hero.image_url)img.src=hero.image_url}
 const f=by.featured;if(f){const t=document.querySelector(".featured-copy h2"),p=document.querySelector(".featured-copy p"),a=document.querySelector(".featured-actions .primary");if(t)t.textContent=f.title;if(p)p.textContent=f.description;if(a)a.href=f.link_url||"shop.html"}
}catch{}}
function renderPopular(){const el=document.getElementById("popularGames");if(!el)return;el.innerHTML=GAMES.slice(0,4).map((g,i)=>'<a class="gr-popular-card" href="game.html?game='+encodeURIComponent(g.slug)+'"><span class="gr-rank">0'+(i+1)+'</span><img src="'+esc(g.image_url)+'" alt="'+esc(g.name)+'"><div><small>'+esc(g.tag||"TOP UP")+'</small><b>'+esc(g.name)+'</b><span>'+esc(g.unit)+' • شحن ↗</span></div></a>').join("")}
function renderGames(){const el=document.querySelector(".neo-game-grid");if(!el)return;el.innerHTML=GAMES.map((g,i)=>'<a class="neo-game-card '+(i===0?"wide":"")+'" href="game.html?game='+encodeURIComponent(g.slug)+'"><img src="'+esc(g.image_url)+'" alt="'+esc(g.name)+'" loading="lazy"><div><small>'+esc(g.tag||"TOP UP")+'</small><h3>'+esc(g.name)+'</h3><b>'+esc(g.unit)+' ↗</b></div></a>').join("")}
function promoCard(p){const g=GAMES.find(x=>x.slug===String(p.game).toLowerCase())||GAMES[0];if(!g)return "";return '<article class="gr-promo-card"><div class="gr-promo-art"><img src="'+esc(g.image_url)+'" alt="'+esc(g.name)+'"></div><div class="gr-promo-body"><span class="gr-promo-badge">🔥 عرض فعال</span><small>'+esc(g.name)+'</small><h3>'+esc(p.title)+'</h3><p>'+esc(p.package_name||"عرض خاص")+(Number(p.discount_iqd)>0?" • خصم "+Number(p.discount_iqd).toLocaleString("en-US")+" IQD":"")+'</p><div class="gr-promo-bottom"><span class="gr-countdown" data-end="'+new Date(p.ends_at).getTime()+'">--:--:--</span><a href="game.html?game='+encodeURIComponent(g.slug)+'">استفد ↗</a></div></div></article>'}
function timers(){document.querySelectorAll(".gr-countdown").forEach(e=>{const tick=()=>{let s=Math.max(0,Math.floor((+e.dataset.end-Date.now())/1000));e.textContent=[Math.floor(s/3600),Math.floor(s%3600/60),s%60].map(x=>String(x).padStart(2,"0")).join(":")};tick();setInterval(tick,1000)})}
async function promos(){const el=document.getElementById("homePromos");if(!el)return;try{const n=new Date().toISOString(),a=await get("/promotions?select=id,title,game,package_name,discount_iqd,ends_at&active=eq.true&starts_at=lte."+encodeURIComponent(n)+"&ends_at=gt."+encodeURIComponent(n)+"&order=ends_at.asc&limit=6");el.innerHTML=a.length?a.map(promoCard).join(""):'<div class="gr-promo-empty"><strong>🎁 العروض جاية بالطريق</strong><span>أضفها من لوحة الإدارة وتظهر هنا تلقائياً.</span><a href="shop.html">تصفح الألعاب ↗</a></div>';timers()}catch{el.innerHTML='<div class="gr-promo-empty">تعذر تحميل العروض حالياً.</div>'}}
function featured(){const img=document.getElementById("featuredImage"),title=document.getElementById("featuredTitle"),text=document.getElementById("featuredText"),unit=document.getElementById("featuredUnit"),link=document.getElementById("featuredLink");if(!img||!title||!GAMES.length)return;let i=0;const set=()=>{const g=GAMES[i%GAMES.length];img.src=g.image_url;img.alt=g.name;title.textContent=g.name;text.textContent=g.description||("شحن "+g.unit);unit.textContent=g.unit;link.href="game.html?game="+encodeURIComponent(g.slug)};set();setInterval(()=>{i++;set()},5000)}
(async()=>{await loadGames();renderPopular();renderGames();await loadHome();await promos();featured()})()
})();