(()=>{"use strict";
const U="https://eyjjmacxxcmdzkfqxifo.supabase.co/rest/v1",K="sb_publishable_6ZnjmE7NccV2hrOOZ-FeNQ_OvP3rLlS";
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
async function get(path){const r=await fetch(U+path,{headers:{apikey:K,Authorization:"Bearer "+K}});if(!r.ok)throw new Error("request failed");return r.json()}
let GAMES=[],HOME=[],SERVICES=[];
const byKey=key=>HOME.find(x=>x.section_key===key);
const active=kind=>HOME.filter(x=>x.kind===kind&&x.active).sort((a,b)=>a.sort_order-b.sort_order);
const setText=(id,v)=>{const e=document.getElementById(id);if(e)e.textContent=v||""};
const setLink=(id,label,url)=>{const e=document.getElementById(id);if(e){e.textContent=label||"";e.href=url||"#"}};
const show=(el,on)=>{if(el)el.hidden=!on};
async function load(){[GAMES,HOME,SERVICES]=await Promise.all([get("/game_catalog?select=slug,name,unit,tag,image_url,description,sort_order&active=eq.true&order=sort_order.asc"),get("/home_content?select=*&active=eq.true&order=sort_order.asc"),get("/services_catalog?select=slug,name,description,icon,href,sort_order&active=eq.true&order=sort_order.asc")]);renderAll()}
function renderAll(){renderAnnouncement();renderHero();renderStats();renderMarquee();renderFeatured();renderLive();renderPromos();renderPopular();renderGames();renderServices();renderIraq();renderRewards();renderRewardsPromo();rotateFeatured()}
function renderAnnouncement(){const x=byKey("announcement"),e=document.getElementById("homeAnnouncement");if(!e)return;show(e,!!x);if(x)e.innerHTML=esc(x.title)+(x.description?" — "+esc(x.description):"")+(x.link_url?' <a href="'+esc(x.link_url)+'">'+esc(x.cta_label||"اكتشف")+' ←</a>':"")}
function renderHero(){const x=byKey("hero"),el=document.getElementById("homeHero");if(!el)return;show(el,!!x);if(!x)return;setText("heroKicker",x.subtitle||"GAME RUSH IRAQ");const t=document.getElementById("heroTitle");if(t){const p=String(x.title||"").split("\\n");t.innerHTML=p.map((v,i)=>i?"<span>"+esc(v)+"</span>":esc(v)).join("<br>")}setText("heroDescription",x.description);setLink("heroPrimary",x.cta_label||"ابدأ الشحن الآن",x.link_url||"#games");const img=document.getElementById("heroImage");if(img){img.src=x.image_url||"";img.alt=x.title||"GameRush"}["heroFloatA","heroFloatB"].forEach((id,i)=>{const g=GAMES[i+1]||GAMES[i],e=document.getElementById(id);if(e&&g){e.src=g.image_url;e.alt=g.name}})}
function renderStats(){const el=document.getElementById("homeStats"),rows=active("stat");if(!el)return;el.innerHTML=rows.map(x=>"<div><strong>"+esc(x.icon)+"</strong><b>"+esc(x.title)+"</b><span>"+esc(x.description)+"</span></div>").join("");show(el,rows.length>0)}
function renderMarquee(){const el=document.getElementById("homeMarquee"),x=byKey("marquee");if(!el)return;show(el,!!x);if(x)el.innerHTML="<span>"+esc(x.icon)+" "+esc(x.title)+"</span><i>•</i><span>"+esc(x.description)+"</span>"}
function renderFeatured(){const x=byKey("featured"),el=document.getElementById("homeFeatured");if(!el)return;show(el,!!x);if(!x)return;setText("featuredKicker",x.subtitle||"SHOP • TOP UP • PLAY");setText("featuredHeading",x.title);setText("featuredDescription",x.description);setLink("featuredPrimary",x.cta_label||"ابدأ الآن",x.link_url||"shop.html")}
function renderLive(){const rows=active("live_card"),el=document.getElementById("homeLive");if(!el)return;show(el,rows.length>0);const box=document.getElementById("homeLiveGrid");if(box)box.innerHTML=rows.map(x=>'<a href="'+esc(x.link_url||"#")+'" class="neo-live-card"><span class="neo-live-icon">'+esc(x.icon)+'</span><div><b>'+esc(x.title)+'</b><small>'+esc(x.description)+'</small></div><em>↗</em></a>').join("")}
function promoCard(p){const g=GAMES.find(x=>x.slug===String(p.game).toLowerCase())||GAMES[0];if(!g)return "";return '<article class="gr-promo-card"><div class="gr-promo-art"><img src="'+esc(g.image_url)+'" alt="'+esc(g.name)+'"></div><div class="gr-promo-body"><span class="gr-promo-badge">🔥 عرض فعال</span><small>'+esc(g.name)+'</small><h3>'+esc(p.title)+'</h3><p>'+esc(p.package_name||"عرض خاص")+(Number(p.discount_iqd)>0?" • خصم "+Number(p.discount_iqd).toLocaleString("en-US")+" IQD":"")+'</p><div class="gr-promo-bottom"><span class="gr-countdown" data-end="'+new Date(p.ends_at).getTime()+'">--:--:--</span><a href="game.html?game='+encodeURIComponent(g.slug)+'">استفد ↗</a></div></div></article>'}
function timers(){document.querySelectorAll(".gr-countdown").forEach(e=>{const tick=()=>{let s=Math.max(0,Math.floor((+e.dataset.end-Date.now())/1000));e.textContent=[Math.floor(s/3600),Math.floor(s%3600/60),s%60].map(x=>String(x).padStart(2,"0")).join(":")};tick();setInterval(tick,1000)})}
async function renderPromos(){const el=document.getElementById("homePromos");if(!el)return;try{const n=new Date().toISOString(),a=await get("/promotions?select=id,title,game,package_name,discount_iqd,ends_at&active=eq.true&starts_at=lte."+encodeURIComponent(n)+"&ends_at=gt."+encodeURIComponent(n)+"&order=ends_at.asc&limit=6");el.innerHTML=a.length?a.map(promoCard).join(""):'<div class="gr-promo-empty"><strong>🎁 العروض جاية بالطريق</strong><span>أضفها من لوحة الإدارة وتظهر هنا تلقائياً.</span><a href="shop.html">تصفح الألعاب ↗</a></div>';timers()}catch{el.innerHTML='<div class="gr-promo-empty">تعذر تحميل العروض حالياً.</div>'}}
function renderPopular(){const el=document.getElementById("popularGames");if(!el)return;el.innerHTML=GAMES.slice(0,4).map((g,i)=>'<a class="gr-popular-card" href="game.html?game='+encodeURIComponent(g.slug)+'"><span class="gr-rank">0'+(i+1)+'</span><img src="'+esc(g.image_url)+'" alt="'+esc(g.name)+'"><div><small>'+esc(g.tag||"TOP UP")+'</small><b>'+esc(g.name)+'</b><span>'+esc(g.unit)+' • شحن ↗</span></div></a>').join("")}
function renderGames(){const el=document.getElementById("homeGameGrid"),sec=document.getElementById("games");if(!el)return;el.innerHTML=GAMES.map((g,i)=>'<a class="neo-game-card '+(i===0?"wide":"")+'" href="game.html?game='+encodeURIComponent(g.slug)+'"><img src="'+esc(g.image_url)+'" alt="'+esc(g.name)+'" loading="lazy"><div><small>'+esc(g.tag||"TOP UP")+'</small><h3>'+esc(g.name)+'</h3><b>'+esc(g.unit)+' ↗</b></div></a>').join("");if(sec)sec.hidden=!GAMES.length}
function renderServices(){const el=document.getElementById("homeServices"),x=byKey("services_intro");if(!el)return;el.innerHTML=SERVICES.map(s=>'<a class="service" href="'+esc(s.href||"#")+'">'+esc(s.icon||"🎮")+'<b>'+esc(s.name)+'</b><span>'+esc(s.description)+'</span></a>').join("");setText("servicesKicker",x?.subtitle||"أكثر من شحن ألعاب");setText("servicesTitle",x?.title||"خدماتنا")}
function renderIraq(){const x=byKey("iraq_banner"),el=document.getElementById("homeIraqBanner");if(!el)return;show(el,!!x);if(x){setText("iraqSubtitle",x.subtitle);setText("iraqTitle",x.title);setText("iraqDescription",x.description);setText("iraqIcon",x.icon||"🇮🇶")}}
function renderRewards(){const rows=active("reward"),x=byKey("rewards_intro"),el=document.getElementById("rewards");if(!el)return;show(el,rows.length>0||!!x);setText("rewardsKicker",x?.subtitle||"برنامج الولاء");setText("rewardsTitle",x?.title||"نقاطك لها قيمة");const box=document.getElementById("homeRewards");if(box)box.innerHTML=rows.map(r=>'<div class="reward"><strong>'+esc(r.icon)+'</strong><h3>'+esc(r.title)+'</h3><p>'+esc(r.description)+'</p></div>').join("")}
function renderRewardsPromo(){const x=byKey("rewards_promo")||byKey("rewards_intro"),el=document.getElementById("homeRewardsPromo");if(!el)return;show(el,!!x);if(x){setText("rewardsPromoKicker",x.subtitle||"GameRush Rewards");setText("rewardsPromoTitle",x.title||"كل طلب يقرّبك للمكافأة 🎁");setText("rewardsPromoDescription",x.description);setLink("rewardsPromoLink",x.cta_label||"اعرف أكثر",x.link_url||"#rewards")}}
function rotateFeatured(){const img=document.getElementById("featuredImage"),title=document.getElementById("featuredTitle"),text=document.getElementById("featuredText"),unit=document.getElementById("featuredUnit"),link=document.getElementById("featuredLink");if(!img||!title||!GAMES.length)return;let i=0;const set=()=>{const g=GAMES[i%GAMES.length];img.src=g.image_url;img.alt=g.name;title.textContent=g.name;text.textContent=g.description||("شحن "+g.unit);unit.textContent=g.unit;link.href="game.html?game="+encodeURIComponent(g.slug)};set();setInterval(()=>{i++;set()},5000)}
load().catch(e=>console.error("GameRush homepage load failed",e));
})();